# Generated by Django 4.1.7 on 2023-03-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
            ],
        ),
        migrations.CreateModel(
            name='MOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('department', models.CharField(max_length=255, verbose_name='Отдел')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('u_m', models.CharField(max_length=255, verbose_name='Единица измерения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.holding', verbose_name='холдинг')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invent_num', models.CharField(max_length=255, verbose_name='Ивентарный номер')),
                ('serial_num', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=30)),
                ('account_date', models.DateTimeField(verbose_name='аккаунт_дата')),
                ('MOL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mol', verbose_name='МОЛ')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.property', verbose_name='Имущество')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('floor', models.CharField(max_length=255, verbose_name='Этаж')),
                ('cabinet', models.CharField(max_length=255, verbose_name='Кабинет')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization', verbose_name='организация')),
            ],
        ),
    ]
