# Generated by Django 4.1.7 on 2023-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mol_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
