# Generated by Django 4.1.7 on 2023-04-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_holding_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
