# Generated by Django 4.1.7 on 2023-04-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
        ),
    ]
