# Generated by Django 4.1.7 on 2023-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_inventorylist_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='account_date',
            field=models.DateTimeField(null=True, verbose_name='аккаунт_дата'),
        ),
    ]
