# Generated by Django 4.1.7 on 2023-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inventorylist_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='invent_num',
            field=models.CharField(default='Отсутствует', max_length=255, verbose_name='Ивентарный номер'),
        ),
    ]
