# Generated by Django 4.1.7 on 2023-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_holding_is_deleted_inventorylist_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
