# Generated by Django 4.1.7 on 2023-05-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_mol_inventorylist_mol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Закупка'), (2, 'Перемещение'), (3, 'Списание')], default=2, verbose_name='Тип операции')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(null=True, verbose_name='аккаунт_дата')),
                ('waybill', models.CharField(max_length=255, verbose_name='Накладная')),
                ('fromm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromm', to='core.department', verbose_name='Отдел')),
                ('inventory_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventorylist', verbose_name='Инвертарная запись')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='Отдел')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.type', verbose_name='Тип Операции')),
            ],
        ),
    ]
