# Generated by Django 4.1.7 on 2023-05-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_operation_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='account_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='аккаунт_дата'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fromm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromm', to='core.department', verbose_name='Из отдела'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='В отдел'),
        ),
    ]
