# Generated by Django 4.1.7 on 2023-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_inventorylist_account_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='pdf_file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
