# Generated by Django 4.1.7 on 2023-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operation_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='pdf_file',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
    ]
