# Generated by Django 4.1.7 on 2023-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_operation_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='waybill',
        ),
        migrations.AlterField(
            model_name='operation',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Накладная'),
        ),
    ]
